# Development Dockerfile
FROM maven:3.9-eclipse-temurin-17-alpine

WORKDIR /app

# 1. Archive Structure
COPY pom.xml .
COPY credit-application-service/pom.xml credit-application-service/
COPY risk-central-mock-service/pom.xml risk-central-mock-service/

# 2. Download dependencies
WORKDIR /app/risk-central-mock-service
RUN mvn dependency:go-offline

# 3. Runtime Command
CMD ["mvn", "spring-boot:run"]
